# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deck.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import card_pb2 as card__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='deck.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndeck.proto\x1a\ncard.proto\"\x1c\n\x04\x44\x65\x63k\x12\x14\n\x05\x63\x61rds\x18\x01 \x03(\x0b\x32\x05.Cardb\x06proto3'
  ,
  dependencies=[card__pb2.DESCRIPTOR,])




_DECK = _descriptor.Descriptor(
  name='Deck',
  full_name='Deck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cards', full_name='Deck.cards', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=54,
)

_DECK.fields_by_name['cards'].message_type = card__pb2._CARD
DESCRIPTOR.message_types_by_name['Deck'] = _DECK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Deck = _reflection.GeneratedProtocolMessageType('Deck', (_message.Message,), {
  'DESCRIPTOR' : _DECK,
  '__module__' : 'deck_pb2'
  # @@protoc_insertion_point(class_scope:Deck)
  })
_sym_db.RegisterMessage(Deck)


# @@protoc_insertion_point(module_scope)
