# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import user_pb2 as user__pb2
import deck_pb2 as deck__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='game.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ngame.proto\x1a\nuser.proto\x1a\ndeck.proto\"\x98\x02\n\x04Game\x12\x11\n\x04\x63ode\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x05users\x18\x02 \x03(\x0b\x32\x05.User\x12\x18\n\x04\x64\x65\x63k\x18\x03 \x01(\x0b\x32\x05.DeckH\x01\x88\x01\x01\x12\x1f\n\x05state\x18\x04 \x01(\x0e\x32\x0b.Game.StateH\x02\x88\x01\x01\x12\x1d\n\x04turn\x18\x05 \x01(\x0b\x32\n.Game.TurnH\x03\x88\x01\x01\x1aH\n\x04Turn\x12\x12\n\x05index\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x15\n\x08reversed\x18\x02 \x01(\x08H\x01\x88\x01\x01\x42\x08\n\x06_indexB\x0b\n\t_reversed\"\x1e\n\x05State\x12\t\n\x05LOBBY\x10\x00\x12\n\n\x06INGAME\x10\x01\x42\x07\n\x05_codeB\x07\n\x05_deckB\x08\n\x06_stateB\x07\n\x05_turnb\x06proto3'
  ,
  dependencies=[user__pb2.DESCRIPTOR,deck__pb2.DESCRIPTOR,])



_GAME_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='Game.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOBBY', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INGAME', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=252,
  serialized_end=282,
)
_sym_db.RegisterEnumDescriptor(_GAME_STATE)


_GAME_TURN = _descriptor.Descriptor(
  name='Turn',
  full_name='Game.Turn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='Game.Turn.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reversed', full_name='Game.Turn.reversed', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_index', full_name='Game.Turn._index',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_reversed', full_name='Game.Turn._reversed',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=178,
  serialized_end=250,
)

_GAME = _descriptor.Descriptor(
  name='Game',
  full_name='Game',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='Game.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='users', full_name='Game.users', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deck', full_name='Game.deck', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='Game.state', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='turn', full_name='Game.turn', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GAME_TURN, ],
  enum_types=[
    _GAME_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_code', full_name='Game._code',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_deck', full_name='Game._deck',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_state', full_name='Game._state',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_turn', full_name='Game._turn',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=39,
  serialized_end=319,
)

_GAME_TURN.containing_type = _GAME
_GAME_TURN.oneofs_by_name['_index'].fields.append(
  _GAME_TURN.fields_by_name['index'])
_GAME_TURN.fields_by_name['index'].containing_oneof = _GAME_TURN.oneofs_by_name['_index']
_GAME_TURN.oneofs_by_name['_reversed'].fields.append(
  _GAME_TURN.fields_by_name['reversed'])
_GAME_TURN.fields_by_name['reversed'].containing_oneof = _GAME_TURN.oneofs_by_name['_reversed']
_GAME.fields_by_name['users'].message_type = user__pb2._USER
_GAME.fields_by_name['deck'].message_type = deck__pb2._DECK
_GAME.fields_by_name['state'].enum_type = _GAME_STATE
_GAME.fields_by_name['turn'].message_type = _GAME_TURN
_GAME_STATE.containing_type = _GAME
_GAME.oneofs_by_name['_code'].fields.append(
  _GAME.fields_by_name['code'])
_GAME.fields_by_name['code'].containing_oneof = _GAME.oneofs_by_name['_code']
_GAME.oneofs_by_name['_deck'].fields.append(
  _GAME.fields_by_name['deck'])
_GAME.fields_by_name['deck'].containing_oneof = _GAME.oneofs_by_name['_deck']
_GAME.oneofs_by_name['_state'].fields.append(
  _GAME.fields_by_name['state'])
_GAME.fields_by_name['state'].containing_oneof = _GAME.oneofs_by_name['_state']
_GAME.oneofs_by_name['_turn'].fields.append(
  _GAME.fields_by_name['turn'])
_GAME.fields_by_name['turn'].containing_oneof = _GAME.oneofs_by_name['_turn']
DESCRIPTOR.message_types_by_name['Game'] = _GAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Game = _reflection.GeneratedProtocolMessageType('Game', (_message.Message,), {

  'Turn' : _reflection.GeneratedProtocolMessageType('Turn', (_message.Message,), {
    'DESCRIPTOR' : _GAME_TURN,
    '__module__' : 'game_pb2'
    # @@protoc_insertion_point(class_scope:Game.Turn)
    })
  ,
  'DESCRIPTOR' : _GAME,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:Game)
  })
_sym_db.RegisterMessage(Game)
_sym_db.RegisterMessage(Game.Turn)


# @@protoc_insertion_point(module_scope)
